### ISSUE TITLE
nth day

### ISSUE THREAD

**Issue by islom-kh** [Karpovich-alex/recurent-events#2]
@Karpovich-alex hi, is it available for nth day of month?

**Comment by Karpovich-alex** [comment]
Hi! 
Yes, nth day of month is available.

**Comment by islom-kh** [comment]
hi @Karpovich-alex, i mean last monday ,friday ... of month, pattern BYDAY=-1MO,-2FR, so we can get instance times of events which ebove pattern

**Comment by Karpovich-alex** [comment]
It supports everything from [pg_rrule](https://github.com/Karpovich-alex/pg_rrule)
I'm not sure, but probably yes.
I will be able to test it next week.

**Comment by islom-kh** [comment]
@Karpovich-alex got you, please ping me after you test it. thanks to replying

**Comment by islom-kh** [comment]
Hi @Karpovich-alex, i tested and it is working for -nth day. so i've another question, how can we deploy pg_rrule on remote db, for examle: aws rds

**Comment by Karpovich-alex** [comment]
Unfortunately, aws does not allow users to import extentions not from [list of supported extentions](https://docs.aws.amazon.com/AmazonRDS/latest/PostgreSQLReleaseNotes/postgresql-extensions.html#postgresql-extensions-14x) 
You can use docker image and instalation guide from readme and use EC2 or other VPS.

**Comment by islom-kh** [comment]
@Karpovich-alex thanks to replying

**Comment by islom-kh** [comment]
@Karpovich-alex hi, how to generate sql code of project? or it is impossible?

**Comment by Karpovich-alex** [comment]
Hi,
Firstly you must install [pg_rrule extension](https://github.com/Karpovich-alex/pg_rrule)
Then you must execute scripts from [./src folder](https://github.com/Karpovich-alex/psql-recurrent-events/tree/main/src)  exclude [./src/test folder](https://github.com/Karpovich-alex/psql-recurrent-events/tree/main/src/test)

Example script to automate this:
```
cat /src/init_db.sql | psql postgres
cat /src/event/*.sql | psql postgres
cat /src/utils/*.sql | psql postgres
cat /src/exception_event/*.sql | psql postgres
```

**Comment by islom-kh** [comment]
hi, i mean how to generate pg_rrule extention in sql format

**Comment by Karpovich-alex** [comment]
Im afraid, that you can not generate sql for this extention. You must install it in PostgreSQL using C

**Comment by islom-kh** [comment]
ok, thanks
